### ISSUE TITLE
If requesting the stock with a different language, the order tracker is in that different language

### ISSUE THREAD

**Issue by QwertycowMoo** [Pan-Lang/panlang-ui#28]
yeah. 
If I choose french when putting in hot dog buns as a requested item, in the order tracker it comes up as "pain au hot dog" instead of "hot dogs buns"

**Comment by renzol2** [comment]
one line fix 😌 https://github.com/Pan-Lang/panlang-ui/commit/5a20bf08847bdf3a40499cecac8dee6350425df2
