### ISSUE TITLE
Add an 'About' page or section

### ISSUE THREAD

**Issue by renzol2** [Pan-Lang/panlang-ui#39]
title

**Comment by bhargavgohil25** [comment]
can you also tell what should be added in the about page ?
@renzol2

**Comment by renzol2** [comment]
> can you also tell what should be added in the about page ?
> @renzol2

Ah sorry @Bhargav252000, I shouldn't have put that tag there 😅this is just a checklist for our team and we're keeping this project between just our team, sorry about that!

**Comment by bhargavgohil25** [comment]
No worries @renzol2  
it's okay  
LOL
