### ISSUE TITLE
Changing the quantity of the stock has to be change from an endpoint to a req param

### ISSUE THREAD

**Issue by QwertycowMoo** [Pan-Lang/panlang-ui#56]
Currently we can make a function that changes the stock based on the endpoint id i think but it seems easier to just pass in the stock id as a req parameter and the backend can just get that and process it. Would the req parameter always have to be filled?

Respond if you want a specific function so that we can keep the frontend the same or if its easy enough to change the frontend to send a req param instead of finding a specific endpoint

**Comment by renzol2** [comment]
It's easy enough to change the frontend, so feel free to change the endpoint to whatever it needs to be. So instead of having the endpoint URL include the stock id (current), we would just include the stock id in our request body (proposed)?
