### ISSUE TITLE
Last updated Date on Order Stock Form is invalid

### ISSUE THREAD

**Issue by QwertycowMoo** [Pan-Lang/panlang-ui#75]
![image](https://user-images.githubusercontent.com/55004908/104630705-17748880-5669-11eb-8a58-6ae060133a2b.png)

**Comment by renzol2** [comment]
This is being resolved in #73

**Comment by renzol2** [comment]
Whoops didn't mean to close that, I'll close it when the PR is merged. Anyway, here's a WIP of the stock order cards:

## WIP Stock Order Card
![image](https://user-images.githubusercontent.com/55109467/104631390-cb721580-5661-11eb-8422-d9cbb12bc825.png)
